version: '3'

services:
  python_occ:
    restart: always
    container_name: step2stl
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
       PORT: 5000
